# Codecov configuration

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%

comment:
  layout: "header, diff, files"
  behavior: default

ignore:
  - "tests/"
  - "examples/"
  - "**/__init__.py"
